// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuRZyAhrwoI-XJarHeVGIBR2tkIkOyORQ',
    appId: '1:998828365946:web:c7b70154e96555139143c3',
    messagingSenderId: '998828365946',
    projectId: 'mummy-map-fbbd8',
    authDomain: 'mummy-map-fbbd8.firebaseapp.com',
    storageBucket: 'mummy-map-fbbd8.firebasestorage.app',
    measurementId: 'G-X5WGQH8HZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQlZqgQeBoH-MmmiFsr6KdHJ3na6k16JA',
    appId: '1:998828365946:android:bc9f7c513e70bc2f9143c3',
    messagingSenderId: '998828365946',
    projectId: 'mummy-map-fbbd8',
    storageBucket: 'mummy-map-fbbd8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBta6FydhL2GeYz_QyQJoeOU91FvxCgXH4',
    appId: '1:998828365946:ios:338ab5ac17a6bb619143c3',
    messagingSenderId: '998828365946',
    projectId: 'mummy-map-fbbd8',
    storageBucket: 'mummy-map-fbbd8.firebasestorage.app',
    iosBundleId: 'com.example.mummymap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBta6FydhL2GeYz_QyQJoeOU91FvxCgXH4',
    appId: '1:998828365946:ios:338ab5ac17a6bb619143c3',
    messagingSenderId: '998828365946',
    projectId: 'mummy-map-fbbd8',
    storageBucket: 'mummy-map-fbbd8.firebasestorage.app',
    iosBundleId: 'com.example.mummymap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuRZyAhrwoI-XJarHeVGIBR2tkIkOyORQ',
    appId: '1:998828365946:web:400dec34ec465fdf9143c3',
    messagingSenderId: '998828365946',
    projectId: 'mummy-map-fbbd8',
    authDomain: 'mummy-map-fbbd8.firebaseapp.com',
    storageBucket: 'mummy-map-fbbd8.firebasestorage.app',
    measurementId: 'G-B20MX11VH5',
  );
}
